name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/*
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-pip
          pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Install basic_bot
        run: |
          python3 -m pip install git+https://github.com/littlebee/basic_bot.git@main

      - name: Make .sh executable
        run: chmod +x ./*.sh

      - name: Run tests
        run: ./test.sh
